name: Pull Request Check

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - Develop
      - Test
  workflow_dispatch:

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'oracle'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run tests with Maven
        run: mvn -B test --file pom.xml

  check-style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Checkstyle
        uses: nikitasavinov/checkstyle-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: 'github-pr-check'
          filter_mode: nofilter
          checkstyle_config: 'checkstyle.xml'
          properties_file: 'reviewdog.yml'

      - name: Fail on lint errors (optional)
        run: exit 1
        if: ${{ failure() }}

  create-jar:
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'oracle'
  
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build Jar
        run: mvn package

      - name: Build Package
        run: mkdir staging && cp target/*.jar staging

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: staging

  write-comment-on-unit-test-failure:
    permissions: write-all
    runs-on: ubuntu-latest
    needs: unit-test
    if: failure()
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Write comment
        uses: mshick/add-pr-comment@v2
        with:
          message: 'There were errors during the unit test process.'

  write-comment-on-check-style-failure:
    permissions: write-all
    runs-on: ubuntu-latest
    needs: check-style
    if: failure()
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Write comment
        uses: mshick/add-pr-comment@v2
        with:
          message: 'There were errors during the check style process.'

  write-comment-on-create-jar-failure:
    permissions: write-all
    runs-on: ubuntu-latest
    needs: create-jar
    if: failure()
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Write comment
        uses: mshick/add-pr-comment@v2
        with:
          message: 'There were errors during the creating jar process.'