name: Push confirm build

on:
  push:
    branches:
      - Acceptance
      - Production
  workflow_dispatch:

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'oracle'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run tests with Maven
        run: mvn -B test --file pom.xml

  check-style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Checkstyle
        uses: nikitasavinov/checkstyle-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          filter_mode: nofilter
          checkstyle_config: 'checkstyle.xml'
          properties_file: 'reviewdog.yml'

      - name: Fail on lint errors (optional)
        run: exit 1
        if: ${{ failure() }}

  create-jar:
    runs-on: ubuntu-latest
    needs: unit-test

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'oracle'
  
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build Jar
        run: mvn package

      - name: Build Package
        run: mkdir staging && cp target/*.jar staging

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: staging

  create-issue-on-unit-test-failure:
    permissions: write-all
    runs-on: ubuntu-latest
    needs: unit-test
    if: failure()

    steps:
      - uses: actions/checkout@v4

      - name: Create issue
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: 'Push confirm build Pipeline Failed: Unit Test'
          body: 'There were errors during the unit test process. Please investigate the logs for more details.'

  create-issue-on-check-style-failure:
    permissions: write-all
    runs-on: ubuntu-latest
    needs: check-style
    if: failure()

    steps:
      - uses: actions/checkout@v4

      - name: Create issue
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: 'Push confirm build Pipeline Failed: Check Style'
          body: 'There were errors during the check style process. Please investigate the logs for more details.'

  create-issue-on-create-jar-failure:
    permissions: write-all
    runs-on: ubuntu-latest
    needs: create-jar
    if: failure()

    steps:
      - uses: actions/checkout@v4

      - name: Create issue
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: 'Push confirm build Pipeline Failed: Create Jar'
          body: 'There were errors during the create jar process. Please investigate the logs for more details.'
